"""initial tables

Revision ID: 0b88f6ef68a4
Revises: 
Create Date: 2026-04-12 16:29:54.508433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b88f6ef68a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('analysis_runs_id', sa.String(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('ai_summary_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('analysis_runs_id')
    )
    op.create_index(op.f('ix_analysis_runs_cache_key'), 'analysis_runs', ['cache_key'], unique=False)
    op.create_table('sku',
    sa.Column('sku_id', sa.String(), nullable=False),
    sa.Column('sku_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('sku_id')
    )
    op.create_index(op.f('ix_sku_category'), 'sku', ['category'], unique=False)
    op.create_index(op.f('ix_sku_sku_id'), 'sku', ['sku_id'], unique=False)
    op.create_table('upload_batches',
    sa.Column('upload_batches_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rows_accepted', sa.Integer(), nullable=True),
    sa.Column('rows_rejected', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('upload_batches_id')
    )
    op.create_table('inventory_snapshots',
    sa.Column('inventory_snapshots_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_batches_id', sa.String(), nullable=False),
    sa.Column('sku_id', sa.String(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.sku_id'], ),
    sa.ForeignKeyConstraint(['upload_batches_id'], ['upload_batches.upload_batches_id'], ),
    sa.PrimaryKeyConstraint('inventory_snapshots_id')
    )
    op.create_index(op.f('ix_inventory_snapshots_sku_id'), 'inventory_snapshots', ['sku_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_snapshot_date'), 'inventory_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_upload_batches_id'), 'inventory_snapshots', ['upload_batches_id'], unique=False)
    op.create_table('sales',
    sa.Column('sale_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_batches_id', sa.String(), nullable=False),
    sa.Column('sku_id', sa.String(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('is_return', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.sku_id'], ),
    sa.ForeignKeyConstraint(['upload_batches_id'], ['upload_batches.upload_batches_id'], ),
    sa.PrimaryKeyConstraint('sale_id')
    )
    op.create_index(op.f('ix_sales_sale_date'), 'sales', ['sale_date'], unique=False)
    op.create_index(op.f('ix_sales_sku_id'), 'sales', ['sku_id'], unique=False)
    op.create_index(op.f('ix_sales_upload_batches_id'), 'sales', ['upload_batches_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_upload_batches_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_sku_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_sale_date'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_inventory_snapshots_upload_batches_id'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_snapshot_date'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_sku_id'), table_name='inventory_snapshots')
    op.drop_table('inventory_snapshots')
    op.drop_table('upload_batches')
    op.drop_index(op.f('ix_sku_sku_id'), table_name='sku')
    op.drop_index(op.f('ix_sku_category'), table_name='sku')
    op.drop_table('sku')
    op.drop_index(op.f('ix_analysis_runs_cache_key'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
