"""initial tables — products rename

Revision ID: 92c72a7b275e
Revises: 
Create Date: 2026-04-13 00:47:01.961927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c72a7b275e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('analysis_runs_id', sa.String(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('ai_summary_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('analysis_runs_id')
    )
    op.create_index(op.f('ix_analysis_runs_cache_key'), 'analysis_runs', ['cache_key'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.create_table('upload_batches',
    sa.Column('upload_batches_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rows_accepted', sa.Integer(), nullable=True),
    sa.Column('rows_rejected', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('upload_batches_id')
    )
    op.create_table('inventory_snapshots',
    sa.Column('inventory_snapshots_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_batches_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['upload_batches_id'], ['upload_batches.upload_batches_id'], ),
    sa.PrimaryKeyConstraint('inventory_snapshots_id')
    )
    op.create_index(op.f('ix_inventory_snapshots_product_id'), 'inventory_snapshots', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_snapshot_date'), 'inventory_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_upload_batches_id'), 'inventory_snapshots', ['upload_batches_id'], unique=False)
    op.create_table('sales',
    sa.Column('sale_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_batches_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('is_return', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['upload_batches_id'], ['upload_batches.upload_batches_id'], ),
    sa.PrimaryKeyConstraint('sale_id')
    )
    op.create_index(op.f('ix_sales_product_id'), 'sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_sale_date'), 'sales', ['sale_date'], unique=False)
    op.create_index(op.f('ix_sales_upload_batches_id'), 'sales', ['upload_batches_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_upload_batches_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_sale_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_product_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_inventory_snapshots_upload_batches_id'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_snapshot_date'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_product_id'), table_name='inventory_snapshots')
    op.drop_table('inventory_snapshots')
    op.drop_table('upload_batches')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_analysis_runs_cache_key'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
